name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests
        run: mvn test

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/java-app:latest .

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository }}/java-app:latest

      - name: Output success message
        run: |
          echo "Docker image successfully built and pushed to GitHub Container Registry!"
          echo "Find it here: https://github.com/orgs/${{ github.repository_owner }}/packages/container/java-app"
